// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVIcp4H_cCrdw71rJigtgoBvQy1mLJ9IQ',
    appId: '1:436161211841:web:8714476ea77bdee66a5340',
    messagingSenderId: '436161211841',
    projectId: 'hype-poc',
    authDomain: 'hype-poc.firebaseapp.com',
    storageBucket: 'hype-poc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5D3u0FeamfvC2oTlcF6lNQIizTLjPYGI',
    appId: '1:436161211841:android:3eefcb7962b459776a5340',
    messagingSenderId: '436161211841',
    projectId: 'hype-poc',
    storageBucket: 'hype-poc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYKKCxUBiwh6ARmvQpqL9IIdkuRVkPj4A',
    appId: '1:436161211841:ios:8f8bffbdb7f944ad6a5340',
    messagingSenderId: '436161211841',
    projectId: 'hype-poc',
    storageBucket: 'hype-poc.appspot.com',
    iosClientId: '436161211841-12ofqhq0n6l2dl9l81ctk5n6r17dasrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYKKCxUBiwh6ARmvQpqL9IIdkuRVkPj4A',
    appId: '1:436161211841:ios:8f8bffbdb7f944ad6a5340',
    messagingSenderId: '436161211841',
    projectId: 'hype-poc',
    storageBucket: 'hype-poc.appspot.com',
    iosClientId: '436161211841-12ofqhq0n6l2dl9l81ctk5n6r17dasrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.hello',
  );
}
